--  FLYOLOGY_SERDE_TEST_FIXTURE_ONLY
--  Generated by serde-generator-v1; do not edit.
--  Generator source SHA-256: 5047e295ed16e87065c5317676e8934edd1dce64323ec868308747f1aed1fe62
--  Type IR commit: 78e6726a80d02b22f573fed3f65538cafd89fc0d
--  Type IR source SHA-256: 92aa85c19c3d0dcfd531f42b75743559efd4f80919942a9acce5f5e15d323c4a
--  Type IR semantic SHA-256: e5f5da08e77e057960fe9ab987b3400e5557a017ae62fcdaa8d4e376042d7f76
--  Overlay SHA-256: 0d1a7e71b11a7c2f24b5ab4f08af016fcbc770db41c0b9af40f47c1f5334ae63
with Flyology_Serde.Adapters.Signed_Integers;
with Flyology_Serde.Adapters.Unsigned_Integers;
with Flyology_Serde.Data_Model;
with Flyology_Serde.Deserialization_Adapters;
with Flyology_Serde.Policies;
with Flyology_Serde.Serialization_Adapters;

package body Flyology.Generated is
   use type Flyology_Serde.Errors.Error_Code;

   package Field_2_Adapter is new Flyology_Serde.Adapters.Signed_Integers
     (Wire_Shape.Signed_16);
   package Field_3_Adapter is new Flyology_Serde.Adapters.Unsigned_Integers
     (Wire_Shape.Unsigned_16);

   Default_Policy : constant Flyology_Serde.Policies.Decode_Policy := (others => <>);

   Serialization_Limits : constant Flyology_Serde.Serialization.Serialization_Limits :=
     (Maximum_Nesting_Depth   => 8,
      Maximum_Container_Items => 16,
      Maximum_Text_Length     => 64,
      Maximum_Byte_Length     => 64,
      Maximum_Logical_Events  => 64);

   procedure Serialize_Value
     (Item  : Wire_Shape.Public_Record;
      Into  : in out Flyology_Serde.Serialization.Serializer'Class;
      Error : in out Flyology_Serde.Errors.Error_Info) is
   begin
      Into.Begin_Record ("wire_shape.public_record", 3, Error);
      Into.Put_Field ("enabled", Error);
      Into.Put_Boolean (Item.Enabled, Error);
      Into.Put_Field ("signed", Error);
      Field_2_Adapter.Serialize_Value (Item.Signed, Into, Error);
      Into.Put_Field ("unsigned", Error);
      Field_3_Adapter.Serialize_Value (Item.Unsigned, Into, Error);
      Into.End_Record (Error);
   end Serialize_Value;

   procedure Begin_Candidate
     (Target : in out Builder; Error : in out Flyology_Serde.Errors.Error_Info) is
   begin
      if Target.Active then
         Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Invalid_State);
      elsif not Target.Initialized then
         Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Invalid_State);
      else
         Target.Candidate := Target.Published;
         Target.Active := True;
         Target.Root_Started := True;
      end if;
   end Begin_Candidate;

   procedure Deserialize_Value
     (From   : in out Flyology_Serde.Deserialization.Deserializer'Class;
      Target : in out Builder;
      Policy : Flyology_Serde.Policies.Decode_Policy;
      Error  : in out Flyology_Serde.Errors.Error_Info)
   is
      pragma Unreferenced (Policy);
      Length    : Flyology_Serde.Data_Model.Length_Information;
      Available : Boolean := False;
      Name      : String (1 .. 64);
      Name_Last : Natural := 0;
      Seen      : array (Positive range 1 .. 3) of Boolean := [others => False];
   begin
      From.Begin_Record ("wire_shape.public_record", Length, Error);
      while Error.Code = Flyology_Serde.Errors.No_Error loop
         From.Next_Field (Name, Name_Last, Available, Error);
         exit when Error.Code /= Flyology_Serde.Errors.No_Error or else not Available;
         Flyology_Serde.Errors.Push_Field (Error, Name (1 .. Name_Last));
         if Name (1 .. Name_Last) = "enabled" then
               if Seen (1) then
                  Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Duplicate_Field);
               else
                  Seen (1) := True;
                  From.Read_Boolean (Target.Candidate.Enabled, Error);
               end if;
         elsif Name (1 .. Name_Last) = "signed" then
               if Seen (2) then
                  Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Duplicate_Field);
               else
                  Seen (2) := True;
                  Field_2_Adapter.Deserialize_Candidate (From, Target.Candidate.Signed, Error);
               end if;
         elsif Name (1 .. Name_Last) = "unsigned" then
               if Seen (3) then
                  Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Duplicate_Field);
               else
                  Seen (3) := True;
                  Field_3_Adapter.Deserialize_Candidate (From, Target.Candidate.Unsigned, Error);
               end if;
         else
            Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Unknown_Field);
         end if;
         exit when Error.Code /= Flyology_Serde.Errors.No_Error;
         Flyology_Serde.Errors.Pop (Error);
      end loop;
      if Error.Code = Flyology_Serde.Errors.No_Error then
         From.End_Record (Error);
      end if;
      if Error.Code = Flyology_Serde.Errors.No_Error and then not Seen (1) then
         Flyology_Serde.Errors.Push_Field (Error, "enabled");
         Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Missing_Field);
      end if;
      if Error.Code = Flyology_Serde.Errors.No_Error and then not Seen (2) then
         Flyology_Serde.Errors.Push_Field (Error, "signed");
         Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Missing_Field);
      end if;
      if Error.Code = Flyology_Serde.Errors.No_Error and then not Seen (3) then
         Flyology_Serde.Errors.Push_Field (Error, "unsigned");
         Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Missing_Field);
      end if;
   end Deserialize_Value;

   procedure Commit_Candidate
     (Target : in out Builder; Error : in out Flyology_Serde.Errors.Error_Info) is
   begin
      if not Target.Active or else not Target.Root_Started then
         Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Invalid_State);
      else
         Target.Published := Target.Candidate;
         Target.Initialized := True;
         Target.Active := False;
         Target.Root_Started := False;
      end if;
   end Commit_Candidate;

   procedure Rollback_Candidate (Target : in out Builder) is
   begin
      if Target.Root_Started then
         Target.Active := False;
         Target.Root_Started := False;
      end if;
   exception
      when others =>
         null;
   end Rollback_Candidate;

   package Serialization_Root is new Flyology_Serde.Serialization_Adapters
     (Source_Type      => Wire_Shape.Public_Record,
      Limits           => Serialization_Limits,
      Serialize_Value => Serialize_Value);

   package Deserialization_Root is new Flyology_Serde.Deserialization_Adapters
     (Builder_Type       => Builder,
      Policy             => Default_Policy,
      Begin_Candidate    => Begin_Candidate,
      Deserialize_Value  => Deserialize_Value,
      Commit_Candidate   => Commit_Candidate,
      Rollback_Candidate => Rollback_Candidate);

   procedure Initialize
     (Target : in out Builder;
      Value  : Wire_Shape.Public_Record;
      Error  : in out Flyology_Serde.Errors.Error_Info) is
   begin
      if Error.Code /= Flyology_Serde.Errors.No_Error then
         return;
      elsif Target.Active then
         Flyology_Serde.Errors.Fail (Error, Flyology_Serde.Errors.Invalid_State);
      else
         Target.Published := Value;
         Target.Candidate := Value;
         Target.Initialized := True;
         Target.Root_Started := False;
      end if;
   end Initialize;

   function Has_Value (Target : Builder) return Boolean
   is (Target.Initialized and then not Target.Active);

   function Value (Target : Builder) return Wire_Shape.Public_Record
   is (Target.Published);

   procedure Serialize
     (Item  : Wire_Shape.Public_Record;
      Into  : in out Flyology_Serde.Serialization.Serializer'Class;
      Error : in out Flyology_Serde.Errors.Error_Info) is
   begin
      Serialization_Root.Serialize (Item, Into, Error);
   end Serialize;

   procedure Deserialize
     (From   : in out Flyology_Serde.Deserialization.Deserializer'Class;
      Target : in out Builder;
      Error  : in out Flyology_Serde.Errors.Error_Info) is
   begin
      Deserialization_Root.Deserialize (From, Target, Error);
   end Deserialize;
end Flyology.Generated;
