--  FLYOLOGY_SERDE_TEST_FIXTURE_ONLY
--  Generated by serde-generator-v1; do not edit.
--  Generator source SHA-256: 5047e295ed16e87065c5317676e8934edd1dce64323ec868308747f1aed1fe62
--  Type IR commit: 78e6726a80d02b22f573fed3f65538cafd89fc0d
--  Type IR source SHA-256: 92aa85c19c3d0dcfd531f42b75743559efd4f80919942a9acce5f5e15d323c4a
--  Type IR semantic SHA-256: e5f5da08e77e057960fe9ab987b3400e5557a017ae62fcdaa8d4e376042d7f76
--  Overlay SHA-256: 0d1a7e71b11a7c2f24b5ab4f08af016fcbc770db41c0b9af40f47c1f5334ae63
with Wire_Shape;
with Flyology_Serde.Deserialization;
with Flyology_Serde.Errors;
with Flyology_Serde.Serialization;

package Flyology.Generated is
   type Builder is limited private;

   procedure Initialize
     (Target : in out Builder;
      Value  : Wire_Shape.Public_Record;
      Error  : in out Flyology_Serde.Errors.Error_Info);
   function Has_Value (Target : Builder) return Boolean;
   function Value (Target : Builder) return Wire_Shape.Public_Record
   with Pre => Has_Value (Target);

   procedure Serialize
     (Item  : Wire_Shape.Public_Record;
      Into  : in out Flyology_Serde.Serialization.Serializer'Class;
      Error : in out Flyology_Serde.Errors.Error_Info);

   procedure Deserialize
     (From   : in out Flyology_Serde.Deserialization.Deserializer'Class;
      Target : in out Builder;
      Error  : in out Flyology_Serde.Errors.Error_Info);

private
   type Builder is limited record
      Published : Wire_Shape.Public_Record;
      Candidate : Wire_Shape.Public_Record;
      Initialized : Boolean := False;
      Active      : Boolean := False;
      Root_Started : Boolean := False;
   end record;
end Flyology.Generated;
